local argiope = require("argiope")
local function hl(name) return vim.api.nvim_get_hl(0, { name = name, link = false }) end

describe("Language palette selection", function()
  after_each(function()
    argiope.setup()
    vim.cmd.colorscheme("argiope")
    vim.cmd("enew!")
  end)

  it("toggles a palette while keeping native and embedded parsing active", function()
    local bufnr = require("tests.helpers").new_javascript_buffer({ 'const view = html`<main>Hello</main>`' })
    local original = hl("@tag.html")
    local parser = vim.treesitter.get_parser(bufnr)
    argiope.set_language("html", false)
    assert.are.same(hl("@tag"), hl("@tag.html"))
    assert.are.same(hl("@tag"), hl("@tag.argiope_html"))
    assert.are.equal(parser, vim.treesitter.get_parser(bufnr))
    assert.is_truthy(vim.treesitter.highlighter.active[bufnr])
    argiope.toggle_language("html")
    assert.are.same(original, hl("@tag.html"))
    vim.api.nvim_buf_delete(bufnr, { force = true })
  end)

  it("keeps configured defaults across theme changes and restores them on reset", function()
    argiope.setup({ highlight = { languages = { css = false } } })
    vim.cmd.colorscheme("argiope")
    assert.are.same(hl("@string"), hl("@string.css"))
    vim.cmd("ArgiopeLanguage set css html")
    assert.are.equal(hl("@string.html").fg, hl("@string.css").fg)
    vim.cmd("ArgiopeThemeVariant trifasciata")
    assert.are.equal(hl("@string.html").fg, hl("@string.css").fg)
    vim.cmd("ArgiopeLanguage reset css")
    assert.are.same(hl("@string"), hl("@string.css"))
    vim.cmd("ArgiopeLanguage set html false")
    assert.are.same(hl("@tag"), hl("@tag.html"))
  end)

  it("starts other installed parsers with generic colors and no editing overrides", function()
    vim.cmd("enew!")
    local bufnr = vim.api.nvim_get_current_buf()
    vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, { '{"answer": 42}' })
    vim.bo[bufnr].filetype = "json"
    assert.is_truthy(vim.treesitter.highlighter.active[bufnr])
    assert.is_nil(vim.b[bufnr].argiope_previous_indent_options)
    argiope.set_language("json", "css")
    assert.are.equal(hl("@string.css").fg, hl("@string.json").fg)
    assert.are.equal("json", vim.treesitter.get_parser(bufnr):lang())
    argiope.set_language("json", false)
    assert.are.same(hl("@string"), hl("@string.json"))
    vim.api.nvim_buf_delete(bufnr, { force = true })
  end)

  it("lets an external Tree-sitter setup own highlighting", function()
    argiope.setup({ highlight = { auto_start = false }, filetypes = { json = false } })
    vim.cmd("enew!")
    local bufnr = vim.api.nvim_get_current_buf()
    vim.bo[bufnr].filetype = "json"
    assert.is_nil(vim.treesitter.highlighter.active[bufnr])
    vim.treesitter.start(bufnr, "json")
    argiope.setup({ filetypes = { json = true } })
    argiope.detach(bufnr)
    assert.is_truthy(vim.treesitter.highlighter.active[bufnr])
    vim.api.nvim_buf_delete(bufnr, { force = true })
  end)

  it("overlays another colorscheme and restores its highlights when disabled", function()
    vim.cmd.colorscheme("default")
    vim.api.nvim_set_hl(0, "@tag.html", { fg = "#123456", bold = true })
    local original = hl("@tag.html")
    local normal = hl("Normal")
    argiope.setup({ theme = { overlay = true } })
    assert.are.same(normal, hl("Normal"))
    assert.are.equal("default", vim.g.colors_name)
    assert.is_not.equal(original.fg, hl("@tag.html").fg)
    argiope.set_language("html", false)
    assert.are.same(original, hl("@tag.html"))
    argiope.set_language("html", true)
    vim.cmd.colorscheme("default")
    assert.is_not.equal(original.fg, hl("@tag.html").fg)
    argiope.setup({ theme = { overlay = false } })
    assert.are.equal("default", vim.g.colors_name)
  end)

  it("rejects invalid assignments without losing active settings", function()
    argiope.setup({ highlight = { languages = { css = false } } })
    assert.has_error(function() argiope.set_language("css", "missing") end)
    assert.is_false(pcall(argiope.setup, { highlight = { languages = { css = "missing" } } }))
    assert.are.same(hl("@string"), hl("@string.css"))
  end)

  it("keeps generic colors consistent with an inherited base override", function()
    argiope.setup({ theme = { variant = "custom", definitions = {
      custom = { extends = "aurantia", base = { cyan = "#123456" } },
    } } })
    vim.cmd.colorscheme("argiope")
    assert.are.equal(0x123456, hl("@variable").fg)
    argiope.set_language("javascript", false)
    assert.are.equal(0x123456, hl("@variable.javascript").fg)
  end)
end)
