import { resolve } from "node:path";
import { converter, formatHex } from "culori";
import {
  chromaticShadeNames,
  neutralShadeNames,
  theme,
} from "../palette/theme.js";
import { reportFailure, root } from "./runtime.js";

const shadeNames = [...chromaticShadeNames, ...neutralShadeNames];
const toHsl = converter("hsl");

function isColor(value) {
  return value && typeof value === "object" && value.mode === "oklch";
}

function isHsl(value) {
  return value && typeof value === "object" && "hue" in value;
}

function hex(value) {
  if (isColor(value)) {
    return formatHex(value);
  }
  const color = Bun.color(
    `hsl(${value.hue} ${value.saturation}% ${value.lightness}%)`,
    "HEX",
  );
  if (typeof color !== "string") {
    throw new Error("argiope: Bun.color did not return a hexadecimal string");
  }
  return color;
}

function validateTheme() {
  for (const [profileName, profile] of Object.entries(theme.profiles)) {
    if (profile.background !== "dark" && profile.background !== "light") {
      throw new Error(`argiope: ${profileName}.background must be dark or light`);
    }
    for (const [paletteName, palette] of Object.entries(profile.monochrome)) {
      const actual = Object.keys(palette).sort();
      const expected = [...shadeNames].sort();
      if (actual.join("\n") !== expected.join("\n")) {
        throw new Error(
          `argiope: ${profileName}.${paletteName} must define the complete twelve-shade contract`,
        );
      }
      for (const shadeName of shadeNames) {
        const color = palette[shadeName];
        if ((!isColor(color) && !isHsl(color)) || !hex(color)) {
          throw new Error(
            `argiope: ${profileName}.${paletteName}.${shadeName} is not a displayable OKLCH color`,
          );
        }
      }
    }
  }
}

function luaString(value) {
  return JSON.stringify(value);
}

function renderHexEntries(value, depth) {
  const indentation = "  ".repeat(depth);
  const lines = [];
  for (const [name, entry] of Object.entries(value)) {
    if (isColor(entry) || isHsl(entry)) {
      lines.push(`${indentation}${name} = ${luaString(hex(entry))},`);
    } else if (typeof entry === "object" && entry !== null) {
      lines.push(`${indentation}${name} = {`);
      lines.push(...renderHexEntries(entry, depth + 1));
      lines.push(`${indentation}},`);
    } else {
      lines.push(`${indentation}${name} = ${luaString(entry)},`);
    }
  }
  return lines;
}

function renderHslEntries(palette, depth, forceChromaticSaturation) {
  const indentation = "  ".repeat(depth);
  const lines = [];
  for (const [name, color] of Object.entries(palette)) {
    const hsl = isHsl(color) ? {
      h: color.hue,
      s: color.saturation / 100,
      l: color.lightness / 100,
    } : toHsl(color);
    const saturation = forceChromaticSaturation && chromaticShadeNames.includes(name)
      ? 100
      : Math.max(0, Math.min(100, Math.round(hsl.s * 100)));
    lines.push(
      `${indentation}${name} = { hue = ${Math.round(hsl.h || 0)}, saturation = ${saturation}, lightness = ${Math.round(hsl.l * 100)} },`,
    );
  }
  return lines;
}

async function main() {
  validateTheme();
  const output = resolve(root, "lua", "argiope", "generated", "palette.lua");
  const lines = [
    "-- Generated by scripts/generate-palette.js from palette/*.js.",
    "-- Edit the cusphanger profile inputs rather than this file.",
    "return {",
    "  profiles = {",
  ];
  for (const [profileName, profile] of Object.entries(theme.profiles)) {
    lines.push(`    ${profileName} = {`);
    lines.push(`      background = ${luaString(profile.background)},`);
    lines.push("      base = {");
    lines.push(...renderHexEntries(profile.base, 4));
    lines.push("      },");
    lines.push("      monochrome = {");
    lines.push(...renderHexEntries(profile.monochrome, 4));
    lines.push("      },");
    lines.push("      hsl = {");
    for (const [paletteName, palette] of Object.entries(profile.monochrome)) {
      lines.push(`        ${paletteName} = {`);
      lines.push(...renderHslEntries(
        palette,
        5,
        profileName === "day" && paletteName !== "gray",
      ));
      lines.push("        },");
    }
    lines.push("      },");
    lines.push("    },");
  }
  lines.push("  },", "}", "");

  await Bun.write(output, lines.join("\n"));
  console.log(`argiope: generated ${output}`);
}

main().catch(reportFailure);
