import { resolve } from "node:path";
import { theme } from "../palette/theme.js";
import { reportFailure, root } from "./runtime.js";

const shadeNames = [
  "darkest",
  "dim",
  "muted",
  "soft",
  "main",
  "accent",
  "bright",
  "light",
  "gray_dim",
  "gray",
  "gray_light",
  "gray_warm",
];

function hex({ hue, saturation, lightness }) {
  const color = Bun.color(
    `hsl(${hue} ${saturation}% ${lightness}%)`,
    "HEX",
  );
  if (typeof color !== "string") {
    throw new Error("argiope: Bun.color did not return a hexadecimal string");
  }
  return color;
}

function isHsl(value) {
  return "hue" in value;
}

function validateHsl(name, value) {
  for (const component of ["hue", "saturation", "lightness"]) {
    if (!Number.isInteger(value[component])) {
      throw new Error(`argiope: ${name}.${component} must be an integer`);
    }
  }
  if (value.hue < 0 || value.hue > 360) {
    throw new Error(`argiope: ${name}.hue must be between 0 and 360`);
  }
  if (
    value.saturation < 0 ||
    value.saturation > 100 ||
    value.lightness < 0 ||
    value.lightness > 100
  ) {
    throw new Error(
      `argiope: ${name} saturation and lightness must be between 0 and 100`,
    );
  }
}

function validatePalettes() {
  for (const [paletteName, palette] of Object.entries(theme.monochrome)) {
    const actual = Object.keys(palette).sort();
    const expected = [...shadeNames].sort();
    if (actual.join("\n") !== expected.join("\n")) {
      throw new Error(
        `argiope: ${paletteName} must define the complete twelve-shade contract`,
      );
    }
    for (const shadeName of shadeNames) {
      validateHsl(`${paletteName}.${shadeName}`, palette[shadeName]);
    }
  }

  const gold2Chromatic = shadeNames.slice(0, 8).map(
    (shadeName) => theme.monochrome.gold2[shadeName].hue,
  );
  if (Math.min(...gold2Chromatic) !== 20 || Math.max(...gold2Chromatic) !== 80) {
    throw new Error("argiope: gold2 chromatic shades must span 20 to 80 degrees");
  }
  for (const shadeName of ["muted", "soft", "main", "accent", "bright"]) {
    const hue = theme.monochrome.gold2[shadeName].hue;
    if (hue < 40 || hue > 60) {
      throw new Error(
        `argiope: common gold2 shade ${shadeName} must stay in the golden window`,
      );
    }
  }
}

function renderEntries(palette, depth) {
  const indentation = "  ".repeat(depth);
  const lines = [];

  for (const [name, value] of Object.entries(palette)) {
    if (isHsl(value)) {
      lines.push(`${indentation}${name} = "${hex(value)}",`);
    } else {
      lines.push(`${indentation}${name} = {`);
      lines.push(...renderEntries(value, depth + 1));
      lines.push(`${indentation}},`);
    }
  }

  return lines;
}

function renderHslEntries(palette, depth) {
  const indentation = "  ".repeat(depth);
  const lines = [];

  for (const [name, value] of Object.entries(palette)) {
    if (isHsl(value)) {
      lines.push(
        `${indentation}${name} = { hue = ${value.hue}, saturation = ${value.saturation}, lightness = ${value.lightness} },`,
      );
    } else {
      lines.push(`${indentation}${name} = {`);
      lines.push(...renderHslEntries(value, depth + 1));
      lines.push(`${indentation}},`);
    }
  }

  return lines;
}

async function main() {
  validatePalettes();
  const output = resolve(root, "lua", "argiope", "generated", "palette.lua");
  const lines = [
    "-- Generated by scripts/generate-palette.js from palette/theme.js.",
    "-- Edit the HSL source rather than this file.",
    "return {",
    ...renderEntries(theme, 1),
    "  hsl = {",
    "    monochrome = {",
    ...renderHslEntries(theme.monochrome, 3),
    "    },",
    "  },",
    "}",
    "",
  ];

  await Bun.write(output, lines.join("\n"));
  console.log(`argiope: generated ${output}`);
}

main().catch(reportFailure);
